1MI0700340 Pract 2, Tasks 1-6
tkostadinov004/Introduction_to_programming_pract_FMI pull request #24
Opened 2024-10-14 14:10 UTC by NicoleNG18

Nicole Georgieva
4

2024-10-14 17:36 UTC, tkostadinov004 approved these changes
Супер решения, с изключение на една забележка по имплементацията на 4-та задача

2024-10-14 17:36 UTC, tkostadinov004 commented on Pract 02/Task04.cpp
> +	bool areCrossing = (b >= c && b <= d) || (a >= c && a <= d);
Какво ще стане, ако единия интервал се съдържа напълно в другия? Например, ако имаш [1; 15] и [8; 10], какъв би трябвало да бъде резултата?

2024-10-14 17:38 UTC, tkostadinov004 requested changes
Супер решения, с изключение на една забележка по имплементацията на 4-та задача

2024-10-14 21:35 UTC, NicoleNG18 commented
Направих го пак. Разчертах ги и видях, че може да стане по друг вариант и да се съкрати. Има скрийншот на скицата ми в readme.md-то на Pract02. Дано този път имам успех

2024-10-15 06:59 UTC, tkostadinov004 approved these changes
Супер решение!

2024-10-15 06:59 UTC, closed without merging