3IM0700328, Pract 02, Tasks 1- 6
tkostadinov004/Introduction_to_programming_pract_FMI pull request #25
Opened 2024-10-14 17:19 UTC by viki441

Viktoriya Mitova
4

2024-10-14 17:31 UTC, tkostadinov004 requested changes

2024-10-14 17:31 UTC, tkostadinov004 commented on Pract 02/Task06.cpp
> +    currentPrice = cheeseburger * cheeseburgerAmount + fishMenu * fishMenuAmount
Не инициализирай currentPrice на 11 ред, а тук, защото преди това не я използваш за нищо

2024-10-14 17:31 UTC, tkostadinov004 commented on Pract 02/Task06.cpp
> +    int dessert = (60 - (int)currentPrice) >> 31; // if sum > 60 = -1 if sum < 60 = 0
Това работи. Искам обаче да знам как работи и какво се случва точно, защото побитови оператори още не сме учили

2024-10-14 17:31 UTC, tkostadinov004 commented on Pract 02/Task05.cpp
> +    std::cout << (firstHalf == secondHalf) ? 0 : 1;
Не ползвай тернарен все още. Няма го изрично написано като изискване, но на практикума всеки път казваме, че за решение на задачите се ползват само нещата, изучени досега

2024-10-14 17:31 UTC, tkostadinov004 commented on Pract 02/Task04.cpp
> +	std::cout << ((b < c || d < a) ? 0 : 1);
Решението е вярно, но е малко объркващо, основно заради тернарния (който поне за тази седмица не трябва да ползваш). Можеш да вземеш отрицанието на израза _(b < c || d < a)_, тоест _!(b < c || d < a)_, което по законите на Де Морган е еквивалентно на: _b >= c && d >= a_

2024-10-14 17:47 UTC, desiggancheva commented on Pract2/Task02.cpp
> +	double reResult = (re1 * re2 + im1 * im2) / (re2 * re2 + im2 * im2);
тук смяташ два пъти един и същи знаменател, по-добре ще е да си го отделиш в променлива, която да приеме стоиност re2 * re2 + im2 * im2

2024-10-15 16:07 UTC, tkostadinov004 approved these changes

2024-10-15 16:07 UTC, tkostadinov004 commented on Pract 02/Task05.cpp
> +    bool result = firstHalf - secondHalf;
Вярно е. Може просто да провериш дали firstHalf и secondHalf са равни

2024-10-15 16:07 UTC, tkostadinov004 commented on Pract 02/Task06.cpp
> +    int dessert = (60 - (int)currentPrice) >> 31; // if sum > 60 = -1 if sum < 60 = 0
Обяснението ми хареса, браво. По-лесен начин има, да, и той е: _bool dessert = currentPrice > 60_. Ако сумата е по-голяма от 60, ще ти върне 1, а ако е по-малка - 0. След това **fullPrice** ще бъде: _currentPrice + 5 + (dessert * currentPrice * 0.1);_. Ако dessert е 0, в скобите ще имаш умножение на някакви числа с 0, тоест десерт няма да се добави. Ако dessert е 1, в скобите вземаш 10% от currentPrice и ги добавяш

2024-10-15 16:07 UTC, closed without merging