3MI0700328 Pract05, Tasks1-6
tkostadinov004/Introduction_to_programming_pract_FMI pull request #58
Opened 2024-11-05 16:51 UTC by viki441

Viktoriya Mitova
4
Later will add the rest of the tasks

2024-11-05 21:30 UTC, tkostadinov004 requested changes

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task01.cpp
> +    return isAlnum(character) && !isAlpha(character) ? character - 48 : -1;
Какво значи числото 48?

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task01.cpp
> +    return isAlpha(character) ? character + 32 : character;
Какво значи числото 32?

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task01.cpp
> +    return n2 + 1;
Първо, ceiling функцията трябва да приема тип с плаваща запетая, защото това е идеята - да закръглиш число нагоре. Второ, ако въведеш числото 5, ще ти върне 6, което няма логика, защото 5 няма дробна част

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task01.cpp
> +    return n2;
Ако подадеш числото -3.8, трябва да ти върне -4, а не -3

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task02.cpp
> +    for (int j = 1; j <= num; j++) {
За простота на число няма нужда да проверяваш до самото число, можеш да проверяваш до неговия корен

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task03.cpp
> +bool getSum(int number) {
Името на функцията е подвеждащо. Добре е булевите функции да започват с глагол is/has/contains и т.н., за да е ясно, че проверяват за нещо. Защото в случая функцията ти не връща сумата на делителите на число, а връща дали сумата на делителите е равна на числото

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task03.cpp
> +    if (sum  == number) {
Следващите няколко реда е добре да бъдат просто _return sum == number;_

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task05.cpp
> +int num1, num2;
Не прави глобални променливи, лоша практика е, пък и поне за този курс не се предполага да го правите

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task05.cpp
> +    num1 += num2;
Какво, ако искам да конкатенирам 0. Например въведа num1 да е 10 и num2 да е 0. Би трябвало функцията да върне 100, но твоята връща 10

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task06.cpp
> +    numDupl = num;
Направи си няколко отделни функции, за да няма такива преизползвания на променливи

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task08.cpp
> +    for (int num = m; num < n; num++) {
Цикълът трябва да върви до n включително

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task08.cpp
> +        int duplicate = num;
Направи си отделна функция, която маха стотиците от число

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task09.cpp
> +void sortNumber(unsigned long long num) {
Функцията за сортиране на число се предполага да връща число, а не да го принтира. Не принтирай във функции, освен ако не е във функция, специално определена за принтиране

2024-11-05 21:30 UTC, tkostadinov004 commented on Pract 05/Task09.cpp
> +        while (duplicateNum > 0) {
Миналата седмица се разбрахме, че щом взехме функции, отсега нататък няма да е много добра идея да се пишат вложени цикли (освен при някои задачи за матрици)

2024-11-06 09:18 UTC, viki441 commented on Pract 05/Task01.cpp
> +    return isAlnum(character) && !isAlpha(character) ? character - 48 : -1;
Промених първа задача

2024-11-06 09:24 UTC, tkostadinov004 approved these changes

2024-11-06 11:28 UTC, viki441 commented on Pract 05/Task03.cpp
> +    if (sum  == number) {
Поправих трета задача.

2024-11-06 21:47 UTC, tkostadinov004 approved these changes

2024-11-06 21:47 UTC, closed without merging