6MI0700383 Pract 1, Tasks 0-6
tkostadinov004/Introduction_to_programming_pract_FMI pull request #6
Opened 2024-10-06 23:22 UTC by denizdsh

2024-10-07 08:06 UTC, tkostadinov004 requested changes

2024-10-07 08:06 UTC, tkostadinov004 commented on Pract 01/01.cpp
> +	std::string a, b, temp;
Не сме учили std::string, няма и изобщо да го учим в рамките на този курс. Опитай само с неща, обяснявани на лекции/семинари/практикуми

2024-10-07 08:06 UTC, tkostadinov004 commented on Pract 01/01.cpp
> +	std::cout << "*******" << code % 1000;
Втория метод е правилен и верен в рамките на курса.

2024-10-09 14:25 UTC, denizdsh commented on Pract 01/01.cpp
> +	std::string a, b, temp;
махнах го

2024-10-10 08:35 UTC, tkostadinov004 approved these changes

2024-10-10 08:35 UTC, tkostadinov004 commented on Pract 02/02.cpp
Супер решения! Чисто от семантична гледна точка, променливата _dessertCoef_ от 6-та задача би било по-добре да е bool, вместо int, защото това е резултат от проверка. Стойността на bool отново ще е число (0 или 1) и ще се преобразува неявно при умножението на долния ред

2024-10-10 08:35 UTC, closed without merging